### ISSUE TITLE
The code doesn't work as expected

### ISSUE THREAD

**Issue by newaeonweb** [strongloop/loopback4-example-family-tree#3]
Following the readme infos, we have the following error:
```
{
  "errors": [
    {
      "message": "Input Object type Where3Input must define one or more fields."
    },
    {
      "message": "Input Object type WhereInput must define one or more fields."
    },
    {
      "message": "Input Object type Where2Input must define one or more fields."
    }
  ]
}

Any help?
```

**Comment by Alan-Cha** [comment]
@newaeonwen Dang! I think I know what is going on. The OAS contains schemas for objects called “where” that do not contain a `properties` field. The tutorial does not make use of this object so you can just an arbitrary `properties` field. 

I’m on mobile so it’s kind of hard to type but something like:

```
“schema”: {
  “type”: “object”,
  “properties”: {
    “placeholderField”: {
      “type”: “string”
    }
  }
}
```

**Comment by temp3l** [comment]
the deprecated 'oasgraph-cli' only gives a few warning, but will show the demo

```
npm i -g oasgraph-cli

oasgraph http://localhost:3001/openapi.json -p 3000
```

**Comment by Alan-Cha** [comment]
@temp3l Thank you for the suggestion. This issue seems to be related to this [one](https://github.com/IBM/openapi-to-graphql/issues/219). 

I have yet to take a deep dive into this problem but I believe the reason why this happens is that OtG has stricter error handling and edge case resolution.

**Comment by Alan-Cha** [comment]
@newaeonweb @temp3l We just put out a patch that should fix this issue. Please update to version 1.4.1 and tell us if this problem still exists. Thank you!
